---

apiVersion: v1
kind: Service
metadata:
  name: ${BRANCH_NAME}-charts
  namespace: ${BRANCH_NAME}
spec:
  selector:
    app: charts
  ports:
  - protocol: TCP
    port: 80
    targetPort: charts-port
